---
- hosts: localhost
  connection: local

  tasks:
  - name: packages
    import_tasks: ansible/packages.yml
  - name: configuration
    import_tasks: ansible/config.yml
  - name: finalize
    import_tasks: ansible/finalize.yml