---
- name: "install software-properties-common"
  apt:
    update_cache: true
    name: software-properties-common
    state: latest
- name: "setup neovim repo"
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
- name: "install packages"
  apt:
    update_cache: true
    pkg:
    - btop
    - tmux
    - zsh
    - neovim
    - git
    - lsd
- name: "get non-root user name"
  become: false
  vars:
    current_user: "{{ ansible_user_id }}"
  register: current_user
- name: "chsh"
  become: true
  user:
    name: "{{ current_user }}"
    shell: /bin/zsh
- name: "check oh-my-zsh install state"
  become: false
  stat:
    path: "~/.oh-my-zsh"
  register: omz-stat
- name: "install oh-my-zsh"
  become: false
  when: not omz-stat.stat.exists
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
- name: "check p10k state"
  become: false
  stat:
    path: "~/.p10k.zsh"
  register: p10k-stat
- name: "install powerlevel10k"
  when: not p10k-stat.stat.exists
  become: false
  shell: 'git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"'