---
- name: "install software-properties-common"
  apt:
    update_cache: true
    name: software-properties-common
    state: latest
- name: "setup neovim repo"
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
- name: "install packages"
  apt:
    update_cache: true
    name:
    - btop
    - tmux
    - zsh
    - neovim
    state: latest
