---
- name: "install software-properties-common"
  become: true
  apt:
    update_cache: true
    name: software-properties-common
    state: latest
- name: "setup neovim repo"
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
- name: "install packages"
  become: true
  apt:
    update_cache: true
    pkg:
    - btop
    - tmux
    - zsh
    - neovim
    - git
    - lsd
    state: latest
- name: "get non-root user name"
  become: false
  set_fact:
    current_user: "{{ ansible_user_id }}"
    user_home: "{{ lookup('env','HOME') }}"
- debug:
    msg: "{{ current_user }}"
- name: "chsh"
  become: true
  user:
    name: "{{ current_user }}"
    shell: /usr/bin/zsh
- name: "check oh-my-zsh state"
  become: false
  stat:
    path: "~/.oh-my-zsh"
  register: omz_stat
- name: "install oh-my-zsh"
  become: false
  when: not omz_stat.stat.exists
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
- name: "check p10k state"
  become: false
  stat:
    path: "~/.oh-my-zsh/custom/themes/powerlevel10k"
  register: p10k_stat
- name: "install powerlevel10k"
  when: not p10k_stat.stat.exists
  become: false
  shell: 'git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"'
- name: Install Lazygit
  block:
    - name: Fetch Lazygit version
      become: false
      shell: |
        curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": *"v\K[^"]*'
      register: lazygit_version

    - name: Download Lazygit tarball
      become: false
      get_url:
        url: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version.stdout }}/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz"
        dest: /tmp/lazygit.tar.gz

    - name: Extract Lazygit tarball
      become: false
      unarchive:
        src: /tmp/lazygit.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Lazygit
      become: true
      command: install /tmp/lazygit -D -t /usr/local/bin/
- name: "LazyVim setup"
  when: not (ansible_stat.path_exists)
  vars:
    ansible_stat:
      path_exists: "{{ lookup('file', '~/.config/nvim/.git') }}"
  block:
  - name: Clone LazyVim starter repository
    git:
      repo: https://github.com/LazyVim/starter.git
      dest: ~/.config/nvim
      update: yes
  - name: Remove .git directory from LazyVim configuration
    file:
      path: ~/.config/nvim/.git
      state: absent
