---
- name: "install software-properties-common"
  become: true
  apt:
    update_cache: true
    name: software-properties-common
    state: latest

- name: "setup neovim repo"
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: "install packages"
  become: true
  apt:
    update_cache: true
    pkg:
    - btop
    - tmux
    - zsh
    - neovim
    - git
    - lsd
    - ripgrep
    - fd-find
    state: latest

- name: "get non-root user name"
  become: false
  set_fact:
    current_user: "{{ ansible_user_id }}"
    user_home: "{{ lookup('env','HOME') }}"

- debug:
    msg: "{{ current_user }}"

- name: Install Lazygit
  become: false
  homebrew:
    name: jesseduffield/lazygit/lazygit
    state: present

- name: "Install fzf"
  become: false
  homebrew:
    name: fzf
    state: present

- name: "Install Zig"
  become: false
  homebrew:
    name: zig
    state: present
