---
- name: "install software-properties-common"
  become: true
  apt:
    update_cache: true
    name: software-properties-common
    state: latest

- name: "setup neovim repo"
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: "install packages"
  become: true
  apt:
    update_cache: true
    pkg:
    - btop
    - tmux
    - zsh
    - neovim
    - git
    - lsd
    - ripgrep
    - fd-find
    state: latest

- name: "get non-root user name"
  become: false
  set_fact:
    current_user: "{{ ansible_user_id }}"
    user_home: "{{ lookup('env','HOME') }}"

- debug:
    msg: "{{ current_user }}"

- name: "Check LazyGit binary"
  become: false
  stat:
    path: /usr/local/bin/lazygit
  register: lazygit_stat

- name: Install Lazygit
  when: not lazygit_stat.stat.exists
  block:
    - name: Fetch Lazygit version
      become: false
      shell: |
        curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": *"v\K[^"]*'
      register: lazygit_version

    - name: Download Lazygit tarball
      become: false
      get_url:
        url: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version.stdout }}/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz"
        dest: /tmp/lazygit.tar.gz

    - name: Extract Lazygit tarball
      become: false
      unarchive:
        src: /tmp/lazygit.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Lazygit
      become: true
      command: install /tmp/lazygit -D -t /usr/local/bin/
      args:
        creates: /usr/local/bin/lazygit

- name: "Install fzf"
  become: false
  homebrew:
    name: fzf
    state: present

- name: "Install Zig"
  become: false
  homebrew:
    name: zig
    state: present
