---
- name: "install software-properties-common"
  become: true
  apt:
    update_cache: true
    name: software-properties-common
    state: latest

- name: "setup neovim repo"
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: "install packages"
  become: true
  apt:
    update_cache: true
    pkg:
    - btop
    - tmux
    - zsh
    - neovim
    - git
    - lsd
    - ripgrep
    - fd-find
    state: latest

- name: "get non-root user name"
  become: false
  set_fact:
    current_user: "{{ ansible_user_id }}"
    user_home: "{{ lookup('env','HOME') }}"

- debug:
    msg: "{{ current_user }}"

- name: Install Lazygit
  when: not lazygit_stat.stat.exists
  block:
    - name: Fetch Lazygit version
      become: false
      shell: |
        curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": *"v\K[^"]*'
      register: lazygit_version

    - name: Download Lazygit tarball
      become: false
      get_url:
        url: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version.stdout }}/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz"
        dest: /tmp/lazygit.tar.gz

    - name: Extract Lazygit tarball
      become: false
      unarchive:
        src: /tmp/lazygit.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Lazygit
      become: true
      command: install /tmp/lazygit -D -t /usr/local/bin/

- name: Install Linuxbrew
  become: false
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew

- name: Add Homebrew to PATH
  become: false
  shell: |
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  args:
    executable: /bin/bash

- name: "Install fzf"
  become: false
  shell: |
    brew install fzf
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/fzf
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:{{ ansible_env.PATH }}"

- name: "Install Zig"
  become: false
  shell: |
    brew install zig
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/zig
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:{{ ansible_env.PATH }}"
